# Generated by Django 5.1.7 on 2025-08-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening_hours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='capacity_per_slot',
            field=models.PositiveIntegerField(default=1, help_text='Nombre maximum de rendez-vous par créneau.'),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si désactivé, ce jour est considéré comme fermé.'),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text="Durée d'un créneau en minutes (15, 20, 30…)."),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='close_time',
            field=models.TimeField(blank=True, help_text='Heure de fermeture (HH:MM).', null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine (0 = Lundi, 6 = Dimanche).', unique=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='open_time',
            field=models.TimeField(blank=True, help_text="Heure d'ouverture (HH:MM).", null=True),
        ),
    ]
