# Generated by Django 5.1.7 on 2025-07-07 16:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code interne unique du service (ex: NATURALISATION, TITRE_SEJOUR)', max_length=50, unique=True, verbose_name='Code du service')),
                ('label', models.CharField(help_text='Nom lisible du service (ex: Titre de séjour)', max_length=100, verbose_name='Libellé')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tarif affiché pour ce service', max_digits=10, verbose_name='Prix (€)')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['label'],
                'indexes': [models.Index(fields=['code'], name='service_code_idx'), models.Index(fields=['label'], name='service_label_idx')],
            },
        ),
    ]
