# Generated by Django 5.1.7 on 2025-07-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='label',
            field=models.CharField(help_text='Nom lisible du service (ex: Titre de séjour)', max_length=1000, verbose_name='Libellé'),
        ),
    ]
