# Generated by Django 5.1.7 on 2025-10-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_fix_service_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="code",
            field=models.CharField(
                help_text="Code interne unique du service (ex: NATURALISATION, TITRE_SEJOUR)",
                max_length=200,
                unique=True,
                verbose_name="Code du service",
            ),
        ),
    ]
