services:
  - type: web
    name: tds-backend
    env: docker
    region: frankfurt
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /api/ping/  # ou "/" si pas d'API dédiée
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "tds-backend.onrender.com"
      - key: FRONTEND_BASE_URL
        value: "https://tds-frontend.onrender.com"
      - key: FRONTEND_URL
        value: "https://tds-frontend.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://tds-frontend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://tds-frontend.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: tds-db
          property: connectionString
      - key: CELERY_BROKER_URL
        value: "rediss://default:AWE1AAIncDFlYWQyNTRkNjE5Y2M0OWFiYWY2ZjgwY2MwM2RlN2Y0Y3AxMjQ4ODU@able-hawk-24885.upstash.io:6379"
      - key: REDIS_URL
        value: "rediss://default:AWE1AAIncDFlYWQyNTRkNjE5Y2M0OWFiYWY2ZjgwY2MwM2RlN2Y0Y3AxMjQ4ODU@able-hawk-24885.upstash.io:6379"
      - key: REDIS_HOST
        value: "able-hawk-24885.upstash.io"
      - key: REDIS_PORT
        value: "6379"

      # Email (Office365)
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.office365.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_USE_SSL
        value: "False"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: contact@titresdesejour.fr
      - key: SERVER_EMAIL
        value: contact@titresdesejour.fr

      # Scaleway S3
      - key: STORAGE_BACKEND
        value: minio
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        value: documents-clients
      - key: AWS_S3_REGION_NAME
        value: fr-par
      - key: AWS_S3_ENDPOINT_URL
        value: https://s3.fr-par.scw.cloud
      - key: AWS_S3_VERIFY
        value: "True"
      - key: AWS_S3_ADDRESSING_STYLE
        value: path
      - key: BUCKET_USERS_AVATARS
        value: avatars-tds
      - key: BUCKET_CLIENT_DOCUMENTS
        value: documents-clients
      - key: BUCKET_CONTRACTS
        value: contracts
      - key: BUCKET_RECEIPTS
        value: recus

      # wkhtmltopdf
      - key: WKHTMLTOPDF_PATH
        value: /usr/bin/wkhtmltopdf

databases:
  - name: tds-db
    plan: free
    region: frankfurt
    postgresMajorVersion: 15