# Generated by Django 5.1.7 on 2025-09-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatutDossierInterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="code"),
                ),
                ("label", models.CharField(max_length=255, verbose_name="nom affiché")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6b7280", max_length=10, verbose_name="couleur (hexa)"
                    ),
                ),
            ],
            options={
                "verbose_name": "statut interne de dossier",
                "verbose_name_plural": "statuts internes de dossier",
                "ordering": ["label"],
            },
        ),
    ]
