# Generated by Django 5.1.7 on 2025-06-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='contract_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
