# Generated by Django 5.1.7 on 2025-04-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_visa',
            field=models.CharField(blank=True, choices=[('SCHENGEN', 'Visa Schengen'), ('LONG_SEJOUR', 'Visa long séjour'), ('ETUDIANT', 'Visa étudiant'), ('VLS_TS', 'VLS-TS'), ('AUTRE', 'Autre')], max_length=20, null=True, verbose_name='type de visa'),
        ),
    ]
