# Generated by Django 5.1.7 on 2025-06-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payment_contract_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='types_demande',
        ),
        migrations.AddField(
            model_name='client',
            name='type_demande',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='type de demande'),
        ),
    ]
