# Generated by Django 5.1.7 on 2025-04-29 15:50

import api.models.document
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_type_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='URL de la photo de profil (facultative)', max_length=500, null=True, verbose_name='avatar'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('CNI', "Carte d'identité"), ('PASSEPORT', 'Passeport'), ('ACTE_NAISSANCE', 'Acte de naissance'), ('JUSTIFICATIF_DOMICILE', 'Justificatif de domicile'), ('FACTURE', 'Facture'), ('FORMULAIRE', 'Formulaire officiel'), ('PHOTO_IDENTITE', "Photo d'identité"), ('ATTESTATION_HEBERGEMENT', "Attestation d'hébergement"), ('ACTE_MARIAGE', 'Acte de mariage'), ('LIVRET_FAMILLE', 'Livret de famille'), ('CERTIFICAT_SCOLARITE', 'Certificat de scolarité'), ('CONTRAT_TRAVAIL', 'Contrat de travail'), ('FICHE_PAIE', 'Fiche de paie'), ('ATTESTATION_POLE_EMPLOI', 'Attestation Pôle Emploi'), ('JUSTIFICATIF_RESSOURCES', 'Justificatif de ressources'), ('RELEVE_BANCAIRE', 'Relevé bancaire'), ('VISA', 'Visa'), ('PERMIS_SEJOUR', 'Titre ou Permis de séjour'), ('CASIER_JUDICIAIRE', 'Casier judiciaire'), ('AUTRES', 'Autres')], max_length=50)),
                ('file', models.FileField(upload_to=api.models.document.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.lead')),
            ],
        ),
    ]
