# Generated by Django 5.1.7 on 2025-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_avatar_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='statut_dossier',
            field=models.CharField(blank=True, choices=[('EN_ATTENTE', 'En attente'), ('INCOMPLET', 'Incomplet'), ('COMPLET', 'Complet'), ('A_VERIFIER', 'À vérifier'), ('EN_COURS_INSTRUCTION', 'En cours d’instruction'), ('RDV_PRIS', 'Rendez-vous pris'), ('RDV_EFFECTUE', 'Rendez-vous effectué'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('ABANDONNE', 'Abandonné'), ('ANNULE', 'Annulé'), ('ARCHIVE', 'Archivé')], help_text='Suivi interne de l’état d’avancement du dossier', max_length=30, null=True, verbose_name='statut du dossier'),
        ),
    ]
