# Generated by Django 5.1.7 on 2025-06-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_client_types_demande_client_type_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.CharField(choices=[('TITRE_SEJOUR', 'Titre de séjour'), ('REGROUPEMENT_FAMILIAL', 'Regroupement familial'), ('NATURALISATION', 'Naturalisation'), ('RENOUVELLEMENT', 'Renouvellement'), ('SUIVI_NATURALISATION', 'Suivi naturalisation'), ('DEMANDE_VISA', 'Demande de visa'), ('DUPLICATA', 'Duplicata'), ('SUIVI_DOSSIER', 'Suivi dossier'), ('DCEM', 'DCEM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='mode',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CB', 'Carte bancaire'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('PNF', 'Crédit Cofidis (PNL)')], max_length=20),
        ),
    ]
