# Generated by Django 5.1.7 on 2025-05-14 14:57

import api.models.document
import api.storage_backends
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lead_statut_dossier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GOOGLE', 'Google'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'Tiktok'), ('PASSAGE', 'Passage'), ('PUB_METRO', 'Pub métro'), ('BOUCHE_OREILLE', 'Bouche à oreille'), ('FLYERS', 'Flyers'), ('TV', 'TV'), ('RADIO', 'Radio'), ('AUTRES', 'Autres (précisez)')], max_length=30), blank=True, default=list, size=None, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('CNI', "Carte d'identité"), ('PASSEPORT', 'Passeport'), ('ACTE_NAISSANCE', 'Acte de naissance'), ('JUSTIFICATIF_DOMICILE', 'Justificatif de domicile'), ('FACTURE', 'Facture'), ('FORMULAIRE', 'Formulaire officiel'), ('PHOTO_IDENTITE', "Photo d'identité"), ('ATTESTATION_HEBERGEMENT', "Attestation d'hébergement"), ('ACTE_MARIAGE', 'Acte de mariage'), ('LIVRET_FAMILLE', 'Livret de famille'), ('CERTIFICAT_SCOLARITE', 'Certificat de scolarité'), ('CONTRAT_TRAVAIL', 'Contrat de travail'), ('FICHE_PAIE', 'Fiche de paie'), ('ATTESTATION_POLE_EMPLOI', 'Attestation Pôle Emploi'), ('JUSTIFICATIF_RESSOURCES', 'Justificatif de ressources'), ('RELEVE_BANCAIRE', 'Relevé bancaire'), ('VISA', 'Visa'), ('PERMIS_SEJOUR', 'Titre ou Permis de séjour'), ('CASIER_JUDICIAIRE', 'Casier judiciaire'), ('AUTRES', 'Autres')], max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=api.storage_backends.MinioMediaStorage(), upload_to=api.models.document.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='document',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.lead', verbose_name='Lead associé'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi"),
        ),
    ]
