# Generated by Django 5.1.7 on 2025-07-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_status", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadstatus",
            name="label",
            field=models.CharField(
                help_text="Libellé affiché dans l'interface (ex: 'Rendez-vous confirmé').",
                max_length=1000,
                verbose_name="libellé",
            ),
        ),
    ]
