# Generated by Django 5.1.7 on 2025-08-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('booked', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quota de créneau',
                'verbose_name_plural': 'Quotas de créneau',
            },
        ),
    ]
