# Generated by Django 5.1.7 on 2025-07-07 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead_status', '0001_initial'),
        ('leads', '0001_initial'),
        ('statut_dossier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Conseiller à qui ce lead est assigné', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='assigné à'),
        ),
        migrations.AddField(
            model_name='lead',
            name='jurist_assigned',
            field=models.ForeignKey(blank=True, help_text='Juriste responsable du lead (assigné par un administrateur)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_juriste', to=settings.AUTH_USER_MODEL, verbose_name='juriste assigné'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(help_text='Statut actuel du lead (ex: NOUVEAU, RDV_VALIDÉ, etc.)', on_delete=django.db.models.deletion.PROTECT, to='lead_status.leadstatus', verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='lead',
            name='statut_dossier',
            field=models.ForeignKey(blank=True, help_text='Suivi interne de l’état d’avancement du dossier', null=True, on_delete=django.db.models.deletion.PROTECT, to='statut_dossier.statutdossier', verbose_name='statut du dossier'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='lead_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['appointment_date'], name='lead_appointment_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='lead_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['jurist_assigned'], name='lead_jurist_idx'),
        ),
    ]
