# Generated by Django 5.1.7 on 2025-07-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='juriste_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
