# Generated by Django 5.1.7 on 2025-07-28 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_juriste_assigned_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, help_text='Conseillers à qui ce lead est assigné', to=settings.AUTH_USER_MODEL, verbose_name='assignés à'),
        ),
    ]
