# Generated by Django 5.1.7 on 2025-09-04 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_rename_jurists_assigned_lead_jurist_assigned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date et heure de création du lead, utilisée pour la traçabilité et le suivi historique",
                verbose_name="date de création",
            ),
        ),
    ]
