# Generated by Django 5.1.7 on 2025-09-29 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0008_alter_lead_created_at"),
        ("statut_dossier_interne", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="statut_dossier_interne",
            field=models.ForeignKey(
                blank=True,
                help_text="Suivi interne réservé à l’équipe pour l’état d’avancement interne du dossier",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="statut_dossier_interne.statutdossierinterne",
                verbose_name="statut du dossier interne",
            ),
        ),
    ]
