# Generated by Django 5.1.7 on 2025-07-07 16:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant dû (€)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Remise (%)')),
                ('contract_url', models.URLField(blank=True, null=True, verbose_name='Contrat PDF')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('is_signed', models.BooleanField(default=False, verbose_name='Signé ?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
            ],
            options={
                'verbose_name': 'contrat',
                'verbose_name_plural': 'contrats',
                'ordering': ['-created_at'],
            },
        ),
    ]
