# Generated by Django 5.1.7 on 2025-08-12 13:57

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="is_refunded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="refund_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Montant remboursé (€)",
            ),
        ),
    ]
