# Generated by Django 5.1.7 on 2025-09-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_contract_is_refunded_contract_refund_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
