# Generated by Django 5.1.7 on 2025-09-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_contract_is_cancelled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_url",
            field=models.URLField(
                blank=True, max_length=1024, null=True, verbose_name="Contrat PDF"
            ),
        ),
    ]
