# Generated by Django 5.1.7 on 2025-11-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_alter_contract_contract_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="invoice_url",
            field=models.URLField(
                blank=True, max_length=1024, null=True, verbose_name="Facture PDF"
            ),
        ),
    ]
