# Generated by Django 5.1.7 on 2025-09-30 12:32

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("jurist_availability_date", "0001_initial"),
    ]

    operations = [
        # Ajout des nouveaux champs
        migrations.AddField(
            model_name="juristglobalavailability",
            name="date",
            field=models.DateField(
                default=timezone.now,
                help_text="Date du créneau de disponibilité.",
            ),
            preserve_default=False,  # ⚡ pour éviter un défaut permanent en DB
        ),
        migrations.AddField(
            model_name="juristglobalavailability",
            name="repeat_monthly",
            field=models.BooleanField(
                default=False,
                help_text="Si coché, ce créneau est répété chaque mois à la même date.",
            ),
        ),

        # Met à jour les options de modèle
        migrations.AlterModelOptions(
            name="juristglobalavailability",
            options={
                "ordering": ["date", "start_time"],
                "verbose_name": "Disponibilité globale juriste",
                "verbose_name_plural": "Disponibilités globales juristes",
            },
        ),

        # Change la contrainte unique pour utiliser `date`
        migrations.AlterUniqueTogether(
            name="juristglobalavailability",
            unique_together={("date", "start_time", "end_time")},
        ),

        # Supprime l'ancien champ `day_of_week`
        migrations.RemoveField(
            model_name="juristglobalavailability",
            name="day_of_week",
        ),
    ]