# Generated by Django 5.1.7 on 2025-09-30 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jurist_availability_date", "0002_update_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="juristglobalavailability",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date du créneau de disponibilité.",
            ),
        ),
        migrations.AlterField(
            model_name="juristglobalavailability",
            name="end_time",
            field=models.TimeField(help_text="Heure de fin du créneau (HH:MM)."),
        ),
        migrations.AlterField(
            model_name="juristglobalavailability",
            name="start_time",
            field=models.TimeField(help_text="Heure de début du créneau (HH:MM)."),
        ),
    ]
