# Generated by Django 5.1.7 on 2025-09-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jurist_availability_date",
            "0003_alter_juristglobalavailability_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="juristglobalavailability",
            name="repeat_monthly",
        ),
        migrations.AddField(
            model_name="juristglobalavailability",
            name="repeat_weekly",
            field=models.BooleanField(
                default=False,
                help_text="Si coché, ce créneau est répété chaque semaine au même jour de semaine.",
            ),
        ),
    ]
