# Generated by Django 5.1.7 on 2025-07-07 16:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ESPECES", "Espèces"),
                            ("CB", "Carte bancaire"),
                            ("VIREMENT", "Virement"),
                            ("CHEQUE", "Chèque"),
                            ("PNF", "Crédit Cofidis (PNF)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True,
                        help_text="Date de la prochaine échéance prévue si le contrat n'est pas encore soldé.",
                        null=True,
                    ),
                ),
                ("receipt_url", models.URLField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
    ]
