# Generated by Django 5.1.7 on 2025-07-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.JSONField(blank=True, default=list, verbose_name="source d'information")),
                ('civilite', models.CharField(blank=True, choices=[('MADAME', 'Madame'), ('MADEMOISELLE', 'Mademoiselle'), ('MONSIEUR', 'Monsieur')], max_length=15, verbose_name='civilité')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, verbose_name='lieu de naissance')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='pays')),
                ('nationalite', models.CharField(blank=True, max_length=100, verbose_name='nationalité')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('code_postal', models.CharField(blank=True, max_length=20, verbose_name='code postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('date_entree_france', models.DateField(blank=True, null=True, verbose_name='date d’entrée en France')),
                ('custom_demande', models.CharField(blank=True, default='', help_text='À remplir si le service choisi est "Autre"', max_length=255, verbose_name='autre demande (à préciser)')),
                ('demande_deja_formulee', models.BooleanField(blank=True, null=True, verbose_name='demande déjà formulée ?')),
                ('demande_formulee_precise', models.CharField(blank=True, max_length=255, verbose_name='si oui, laquelle ?')),
                ('a_un_visa', models.BooleanField(blank=True, null=True, verbose_name='visa')),
                ('type_visa', models.CharField(blank=True, choices=[('SCHENGEN', 'Visa Schengen'), ('LONG_SEJOUR', 'Visa long séjour'), ('ETUDIANT', 'Visa étudiant'), ('VLS_TS', 'VLS-TS'), ('AUTRE', 'Autre')], max_length=20, null=True, verbose_name='type de visa')),
                ('statut_refugie_ou_protection', models.BooleanField(blank=True, null=True, verbose_name='statut réfugié ou protection subsidiaire')),
                ('situation_familiale', models.CharField(blank=True, choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('CONCUBIN', 'Concubin(e)'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf(ve)')], max_length=20, verbose_name='situation familiale')),
                ('a_des_enfants', models.BooleanField(blank=True, null=True, verbose_name='a des enfants ?')),
                ('nombre_enfants', models.PositiveIntegerField(blank=True, null=True, verbose_name='nombre d’enfants')),
                ('nombre_enfants_francais', models.PositiveIntegerField(blank=True, null=True, verbose_name='nombre d’enfants français')),
                ('enfants_scolarises', models.BooleanField(blank=True, null=True, verbose_name='enfants scolarisés ?')),
                ('naissance_enfants_details', models.TextField(blank=True, verbose_name='détails naissance enfants')),
                ('situation_pro', models.CharField(blank=True, choices=[('CDI', 'En CDI'), ('CDD_INTERIM', 'En CDD / Intérim'), ('INDEPENDANT', 'Profession libérale / Indépendant'), ('ETUDIANT', 'Étudiant'), ('SANS_EMPLOI', 'Sans emploi')], max_length=30, verbose_name='situation professionnelle')),
                ('domaine_activite', models.CharField(blank=True, max_length=255, verbose_name='domaine d’activité')),
                ('nombre_fiches_paie', models.PositiveIntegerField(blank=True, null=True, verbose_name='nombre de fiches de paie')),
                ('date_depuis_sans_emploi', models.DateField(blank=True, null=True, verbose_name='depuis quelle date sans emploi / étudiant')),
                ('logement_type', models.CharField(blank=True, choices=[('LOCATAIRE', 'Locataire'), ('PROPRIETAIRE', 'Propriétaire'), ('HEBERGE', 'Hébergé'), ('AUTRE', 'Autre')], max_length=20, verbose_name='type de logement')),
                ('a_deja_eu_oqtf', models.BooleanField(blank=True, null=True, verbose_name='déjà eu une OQTF ?')),
                ('date_derniere_oqtf', models.DateField(blank=True, null=True, verbose_name='date de la dernière OQTF')),
                ('demarche_en_cours_administration', models.BooleanField(blank=True, null=True, verbose_name='démarche en cours auprès de l’administration ?')),
                ('remarques', models.TextField(blank=True, verbose_name='remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'données client',
                'verbose_name_plural': 'données clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
