# Generated by Django 5.1.7 on 2025-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_anef_email_client_anef_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="date_expiration_visa",
            field=models.DateField(
                blank=True, null=True, verbose_name="date d'expiration du visa"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="demarche_simplifiee_email",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="email du compte Démarches Simplifiées (texte libre)",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="demarche_simplifiee_password",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="mot de passe du compte Démarches Simplifiées",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="has_demarche_simplifiee_account",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="a un compte Démarches Simplifiées ?",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="anef_email",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="email du compte ANEF (texte libre)",
            ),
        ),
    ]
