# Generated by Django 5.1.7 on 2025-07-22 10:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0003_lead_juriste_assigned_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        help_text="Date et heure du rendez-vous",
                        verbose_name="date et heure du rendez-vous",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Note ou objet du rendez-vous (optionnel)",
                        max_length=500,
                        null=True,
                        verbose_name="note",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date de création du rendez-vous",
                        verbose_name="date de création",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur qui a planifié le rendez-vous",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="Lead concerné par ce rendez-vous",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="leads.lead",
                        verbose_name="lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "rendez-vous",
                "verbose_name_plural": "rendez-vous",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="appointment_date_idx"),
                    models.Index(fields=["lead"], name="appointment_lead_idx"),
                    models.Index(
                        fields=["created_by"], name="appointment_createdby_idx"
                    ),
                ],
            },
        ),
    ]
