# Generated by Django 5.1.7 on 2025-07-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialClosingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Nom ou motif de la fermeture (ex : 'Noël', 'Vacances d'été', 'Travaux', etc.)", max_length=100)),
                ('start_date', models.DateField(help_text='Premier jour fermé (inclusif)')),
                ('end_date', models.DateField(help_text='Dernier jour fermé (inclusif)')),
            ],
            options={
                'verbose_name': 'Fermeture exceptionnelle',
                'verbose_name_plural': 'Fermetures exceptionnelles',
                'ordering': ['start_date'],
            },
        ),
    ]
