# Generated by Django 5.1.7 on 2025-09-29 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("special_closing_period", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialclosingperiod",
            options={
                "ordering": ["start_datetime"],
                "verbose_name": "Fermeture exceptionnelle",
                "verbose_name_plural": "Fermetures exceptionnelles",
            },
        ),
        migrations.RemoveField(
            model_name="specialclosingperiod",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="specialclosingperiod",
            name="start_date",
        ),
        migrations.AddField(
            model_name="specialclosingperiod",
            name="end_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Fin de la fermeture (date + heure)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specialclosingperiod",
            name="start_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Début de la fermeture (date + heure)",
            ),
            preserve_default=False,
        ),
    ]
